<?php 
	$frm = $this->frm_search;
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	
	$dbGB = new Application_Model_DbTable_DbGlobal();
	$logo = $this->baseUrl()."/images/logo.jpg";
	$branch_title = $tr->translate("BRAND_TITLE");
?>
<meta charset="utf-8">
<script>
dojo.require("dijit.form.DateTextBox");
</script>
<title><?php echo $tr->translate("CUSTOMER_REPORT");?></title>
<div class="reportblog">
	<div class="content-report">
		<div class="card-box">
	       	<div class="col-sm-12 border-botom">
		   		<div class="col-sm-8 pd-0">
		    		<h4 class="m-b-0"><i class="fa fa-file-text" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('CUSTOMER_REPORT');?></h4>
	    		</div>
	    		<div class="col-sm-4 text-right">
	    		</div>
	    	</div>
	    </div>
	    <div class="card-box">
	   		 <form id="list" name="list" action="" dojoType="dijit.form.Form" method="post">
					<div class="form-group"> 
						<div class="col-md-2 col-sm-2 col-xs-12">
							<?php echo $frm->getElement("adv_search");?>
						</div>
						<div class="col-md-2 col-sm-2 col-xs-12">
							<?php echo $frm->getElement('category');?>
						</div>
						<div class="col-md-2 col-sm-2 col-xs-12">
							<?php echo $frm->getElement('service_id');?>
						</div>
						<div class="col-md-2 col-sm-2 col-xs-12">
							<?php echo $frm->getElement('product_id');?>
						</div>
						<div class="col-md-2 col-sm-2 col-xs-12">
							<?php echo $frm->getElement('start_date');?>
						</div>
						<div class="col-md-2 col-sm-2 col-xs-12">
							<?php echo $frm->getElement('end_date');?>
						</div>
						
					</div>
					<div class="form-group">
						<div class="col-md-2 col-sm-2 col-xs-12">
							<?php echo $frm->getElement('standard');?>
						</div> 
						<div class="col-md-2 col-sm-2 col-xs-12">
							<?php echo $frm->getElement('made_by');?>
						</div> 
						<div class="col-md-2 col-sm-2 col-xs-12">
							<?php echo $frm->getElement('province');?>
						</div>
						<div class="col-md-2 col-sm-2 col-xs-12">
							<input id="district" >
						</div>
						<div class="col-md-2 col-sm-2 col-xs-12">
							<input id="commune" >
						</div>
						<div class="col-md-2 col-sm-2 col-xs-12">
							<input id="village" >
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-2 col-sm-2 col-xs-12">
						<?php echo $frm->getElement('zone_id');?>
						</div>
						<div class="col-md-2 col-sm-2 col-xs-12">
							<?php echo $frm->getElement('street_id');?>
						</div>
						<div class="col-md-2 col-sm-2 col-xs-12">
							<?php echo $frm->getElement('line');?>
						</div>
						<div class="col-md-2 col-sm-2 col-xs-12">
							<?php echo $frm->getElement('floor');?>
						</div> 
						<div class="col-md-2 col-sm-2 col-xs-12">
							<?php echo $frm->getElement('side');?>
						</div>
						<div class="col-md-2 col-sm-2 col-xs-12">
							<?php echo $frm->getElement('start_direction');?>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-2 col-sm-2 col-xs-12">
							<?php echo $frm->getElement('verification');?>
						</div>
						<div class="col-md-2 col-sm-2 col-xs-12">
							
							<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
						</div>
					</div>
				</form>
		</div>
		<div id="divPrint" style="margin: 0 auto;">
		<style>
			.hover:hover{ background: #ccc;}
			.style{
				line-height: 20px;font-size: 14px !important;
				font-family:'Times New Roman','Khmer OS Battambang';
			}
			table { page-break-inside:auto }
			tr{ page-break-inside:avoid; page-break-after:auto; }
			#header {
			  display: table-header-group;
			  page-break-inside:avoid; page-break-after:auto;
			}
			table tr td ul li{text-align: center;list-style: none;line-height: 25px; }
			th{padding: 5px;}
			.hover td{padding: 1px;}
			.hide{visibility: hidden;}
			@media print {
			  div.divFooter {
			    position: fixed;
			    top: 0;
			  	width: 100%;
			  	height: 100px;
			  	bottom:0px;
				margin:0;
			  }
			.hide{visibility: visible; height: 110px;}
			}
			.divFooter table{
				font-family: 'Times New Roman','Khmer OS Battambang';
				margin:0; 
				padding:0; 
				border:none;
			}
			table.content-data{
				border-collapse:collapse;
				border:1px solid #000; 
				font-size:13px;
			}
			table.content-data thead tr.style {
			   line-height: 25px; font-size:12px !important; padding:1px 0px; white-space: nowrap;height: 22px; 
			}
			table.content-data thead tr td{
				padding: 0 5px;
				font-weight: 600;
			}
			table.tb-footer{
			border-collapse:collapse;
			border:1px solid #000; 
			font-size:13px;
			}
			td.bold{ font-weight: 600;}
			td.nowrap {
			    white-space: nowrap;
			}
			tr.data-list td{ padding: 0 5px; }
			table.tb-footer tr{
			 line-height: 14px; font-size:14px; padding:2px 0px; height: 25px;
			}
			.border_bottom {
			    border-bottom: 2px solid #000;
			}
		</style>
		<table style="font-family: 'Times New Roman','Khmer OS Battambang'; width:100%;">
			<tr>
		    	<td align="center">
		        	<div class="divFooter">
			        	<table width="100%">
			            	<tr>
			                	<td width="30%"><img src="<?php echo $logo;?>" height="85px" ></td>
			                	<td width="40%" valign="top">
			                		<ul>
			                			<li style="text-align:center; font-size:<?php echo FONTSIZE_REPORT;?>; font-family:'Khmer OS Muol Light'"><?php echo $branch_title;?></li>
			                			<li style="text-align:center; font-size:<?php echo FONTSIZE_REPORT;?>; font-family:'Khmer OS Muol Light'"><?php echo $tr->translate("CUSTOMER_REPORT");?></li>
			                			<li style="text-align:center; font-size:<?php echo FONTSIZE_REPORT;?>;"><?php if(!empty($this->search['start_date'])){echo date("d-M-Y",strtotime($this->search['start_date'])).' '.$tr->translate('TO').' ';echo date("D-d-M-Y",strtotime($this->search['end_date']));}?></li>
			                		</ul>
			                	</td>
			                    <td width="30%"></td>
			                </tr> 
			            </table>
		            </div>
		        </td>
		    </tr>
		    <tr>
		    	<td id="exportExcel">
		            <table class="content-data" border="1"​ width="100%" cellspacing="0">
		               <thead>
		                 <tr class="hide" style="border:1px solid #000;">
			                <td colspan="17" style="border:1px solid #fff;border-bottom:1px solid #000;"></td>
			             </tr>
		                 <tr bgcolor="#c1d0f3" class="style" align="center" >
		                    <td rowspan="2">&nbsp;<span><?php echo $tr->translate("NUM");?></span>&nbsp;</td>
		                    <td colspan="4">&nbsp;<span><?php echo $tr->translate("CUSTOMER_INFO");?></span>&nbsp;</td>
		                    <td colspan="5">&nbsp;<span><?php echo $tr->translate("OTHER_INFO");?></span>&nbsp;</td>
		                    <td colspan="15">&nbsp;<span><?php echo $tr->translate("LOCATION_INFO");?></span>&nbsp;</td>
		                    <td rowspan="2">&nbsp;<span><?php echo $tr->translate("BY_USER");?></span>&nbsp;</td>
		                </tr>
		                <tr bgcolor="#c1d0f3" class="style" align="center" >
		                    <td><?php echo $tr->translate("CLIENT_NUM");?></td>
		                    <td><?php echo $tr->translate("KH_NAME");?></td>
		                    <td><?php echo $tr->translate("EN_NAME");?></td>
		                    <td><?php echo $tr->translate("SEX");?></td>
		                    
		                    <td><?php echo $tr->translate("CATEGORY");?></td>
		                    <td><?php echo $tr->translate("SERVICE");?></td>
		                    <td><?php echo $tr->translate("PRODUCT");?></td>
		                    <td><?php echo $tr->translate("STANDARD");?></td>
		                    <td><?php echo $tr->translate("MADE_BY");?></td>
		                    
		                    <td><?php echo $tr->translate("CONTACT");?></td>
		                    <td><?php echo $tr->translate("STREET");?></td>
		                    <td><?php echo $tr->translate("ZONE");?></td>
		                    <td><?php echo $tr->translate("LINE");?></td>
		                    <td><?php echo $tr->translate("FLOOR");?></td>
		                    <td><?php echo $tr->translate("VILLAGE");?></td>
		                    <td><?php echo $tr->translate("COMMUNE");?></td>
		                    <td><?php echo $tr->translate("DISTRICT");?></td>
		                    <td><?php echo $tr->translate("PROVINCE");?></td>
		                    <td><?php echo $tr->translate("SIDE");?></td>
		                    <td><?php echo $tr->translate("START_DIRECTION");?></td>
		                    
		                    <td>&nbsp;<span><?php echo $tr->translate("MAP");?></span>&nbsp;</td>
		                    <td>&nbsp;<span><?php echo $tr->translate("PHOTO");?></span>&nbsp;</td>
		                    
		                    <td><?php echo $tr->translate("VERIFICATION");?></td>
		                    <td><?php echo $tr->translate("OTHER");?></td>
		                </tr>
		              </thead>
		              <tbody>
		              	<?php if (!empty($this->rs)) foreach ($this->rs as $key => $rs){?>
		              		<tr class="data-list context-menu-one" oncontextmenu="setrowdata(<?php echo $rs['id'];?>);return false;" > 
		              			<td align="center"><?php echo $key+1;?></td>
		              			<td>
		              			<?php if (!empty($rs['map'])){?>
		              			<a style="color: inherit; text-decoration: none;" href="<?php echo $rs['map'];?>" target="_blank" >
		              			<?php }?>
		              			<?php echo $rs['client_number']?>
		              			<?php if (!empty($rs['map'])){?>
		              			</a>
		              			<?php }?>
		              			</td>
		              			<td class="bold"><?php echo $rs['name_kh']?></td>
		              			<td class="bold"><?php echo $rs['name_en']?></td>
		              			<td align="center"><?php echo $rs['sex']?></td>
		              			
		              			<td align="center" class="nowrap"><?php echo $rs['category']?></td>
		              			<td align="center" class="nowrap"><?php echo $rs['service']?></td>
		              			<td align="center" class="nowrap"><?php echo $rs['product']?></td>
		              			<td align="center" class="nowrap"><?php echo $rs['standard']?></td>
		              			<td align="center" class="nowrap"><?php echo $rs['madeby']?></td>
		              			
		              			<td style=" min-width: 120px; line-height: 12px;  overflow-wrap: break-word;"><?php echo $rs['contact']?></td>
		              			<td align="center" class="nowrap"><?php echo $rs['street']?></td>
		              			<td class="nowrap"><?php echo $rs['zone']?></td>
		              			<td align="center" class="nowrap"><?php echo $rs['line']?></td>
		              			<td align="center" class="nowrap"><?php echo $rs['floor']?></td>
		              			<td class="nowrap"><?php echo $rs['village_name']?></td>
		              			<td class="nowrap"><?php echo $rs['commnune']?></td>
		              			<td class="nowrap"><?php echo $rs['district']?></td>
		              			<td class="nowrap"><?php echo $rs['province']?></td>
		              			<td class="nowrap"><?php echo $rs['side']?></td>
		              			<td class="nowrap"><?php echo $rs['start_direction']?></td>
		              			
		              			<td>
		              			<?php if (!empty($rs['map'])){?>
		              			<a style="color: inherit; text-decoration: none;" href="<?php echo $rs['map'];?>" target="_blank" >
		              			<img src="<?php echo $this->baseUrl()."/images/maps-and-flags.png"; ?>" style=" padding: 3px; width: 40px;"/>
		              			<?php }?>
		              			
		              			<?php if (!empty($rs['map'])){?>
		              			</a>
		              			<?php }?>
		              			</td>
		              			<td>
		              			<?php if (!empty($rs['photo_name'])){
		              				if (file_exists(PUBLIC_PATH."/images/photo/".$rs['photo_name'])){
		              					$images = $this->baseUrl()."/images/photo/".$rs['photo_name'];
		              				?>
		              				<a style="color: inherit; text-decoration: none;" href="<?php echo $images;?>" target="_blank" >
		              				<img src="<?php echo $images; ?>" style=" padding: 1px; width: 50px;"/>
		              				</a>
		              			<?php }}?>
		              			</td>
		              			<td class="nowrap"><?php echo $rs['verification']?></td>
		              			<td class="nowrap"><?php echo $rs['other']?>
		              				<input dojoType="dijit.form.ValidationTextBox" required="true" id="map<?php echo $rs['id'];?>" name="map<?php echo $rs['id'];?>" value="<?php echo $rs['map'];?>" type="hidden" class="fullside">
		              			</td>
		              			<td align="center"><?php echo $rs['user_name']?></td>
		              		</tr>
		              	<?php }?>
		              </tbody>
		              </table>
		              <br />
		              <?php echo $this->footerReport;?>
		    	</td>
		    </tr>
		</table>
		</div>
	</div>
	
</div>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<?php 
$urlProfile = $this->baseUrl()."/report/index/client-profile/id/";
?>
<script type="text/javascript">
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dijit.form.DateTextBox");

var district_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?> );
var commune_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?> );
var village_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?> );

dojo.ready(function(){
	new dijit.form.FilteringSelect({
		store: district_store,
		autoComplete:false,
		queryExpr:'*${0}*',
		required: false,		           
		name: "district",
		id: "district",
		searchAttr: "name",
		class: 'fullside',
			onChange: function() {
				district = dijit.byId('district').get('value');
				if(district==-1){
					showPopupdistrict();
					}
					filterCommune();
			}  
		}, "district");
		 
		new dijit.form.FilteringSelect({
		store: commune,
		autoComplete:false,
		queryExpr:'*${0}*',
		required: false,		           
		name: "commune",
		id: "commune",
		searchAttr: "name",
		class: 'fullside',
			onChange: function() {
				commune = dijit.byId('commune').get('value');
				if(commune==-1){
					showPopupCommune();
				}
				else{
					filterVillage();
				}
	  }
		}, "commune");
		 
		new dijit.form.FilteringSelect({
		store: village_store,
		autoComplete:false,
		queryExpr:'*${0}*',
		required: false,		           
		name: "village",
		id: "village",
		searchAttr: "name",
		class: 'fullside',
			onChange: function() {
				vill = dijit.byId('village').get('value');
				if(vill==-1){
					showPopupVillage();
				}
			}
		}, "village");
});
url_getdistrict = '<?php echo $this->url(array('module'=>'other','controller'=>'district','action'=>'get-district'));?>';
function filterDistrict(){
	pro_id = dijit.byId('province').get('value');
	if(pro_id==0){
		return false;}
		dojo.xhrPost({
			url:url_getdistrict,	
			content:{ 
				'pro_id': pro_id
			},
			handleAs:"json",
			load: function(data) {	
				district_store  = getDataStorefromJSON('id','name', data);		
			    dijit.byId('district').set('store', district_store);
			},
			error: function(err) {
			}
		});	
}
url_getcommune = '<?php echo $this->url(array('module'=>'other','controller'=>'commune','action'=>'get-commune'));?>';
function filterCommune(){
	distict_id = dijit.byId('district').get('value');
	if(distict_id==0){
		return false;}
	dojo.xhrPost({
		url:url_getcommune,	
		content:{ 
			'district_id': distict_id
		},
		handleAs:"json",
		load: function(data) {	
			commune_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('commune').set('store', commune_store);
		},
		error: function(err) {
		}
	});
}
url_getvillage = '<?php echo $this->url(array('module'=>'other','controller'=>'village','action'=>'get-allvillage'));?>';
function filterVillage(){
	commune_id = dijit.byId('commune').get('value');
	if(commune_id==0){
		return false;}
		dojo.xhrPost({
			url:url_getvillage,	
			content:{ 
				'commune_id': commune_id
			},
			handleAs:"json",
			load: function(data) {	
				village_store  = getDataStorefromJSON('id','name', data);		
			    dijit.byId('village').set('store', village_store);
			},
			error: function(err) {
				alert(err);
			}
		});
}
var row=0;
var url="";
$(function(){
	$.contextMenu({
		selector: '.context-menu-one', 
		callback: function(key, options) {
		
			var m = "clicked: " + key;
			if(key=="profile"){
				url='<?php echo $urlProfile;?>';
			}else if(key=="map"){
				vill = dijit.byId('map'+row).get('value');
				if(vill==""){
					alert("<?php echo $tr->translate("NO_MAP");?>");
					return false;
				}
				url = vill;
			}
			gotoAction();
		},
		items: {
			"profile": {name: "<?php echo $tr->translate("CUSTOMER_PROFILE");?>", icon: "fa-file-text"},
			"map": {name: "<?php echo $tr->translate("MAP");?>", icon: "fa-file-text"},
		}
	});
});
function setrowdata(index){
	row = index;
}
var recordid ='';
function gotoAction(){
	 window.open(url+row, '_blank');
}
</script>