<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('EDIT_CLIENT'));
?>	
<?php  $frm = $this->frm_client;?>

<style>
.button_browse {
    position: relative;
    overflow: hidden;
    text-align: center;
    width: 100%;
    height: 30px;
    cursor: pointer;
    background: #fbf9f9;
    border: 1px solid #e8e8e8;
}
.button_browse span {
    line-height: 33px;
    font-weight: 600;
    cursor: pointer;
}
input.btn_borwse_image {
    position: absolute;
    width: 100%;
    height: 35px;
    top: 0;
    left: 0;
    z-index: 2;
    opacity: 0;
    cursor: pointer;
}
.account-image {
    border: solid 1px #eee;
    width: 190px;
}
.image-box {
    text-align: center;
}
.image-box img {
    width: 190px;
    height: 130px;
    border: solid 1px #eee;
}
.btn-reset{
	background: #c00;
    color: #fff;
}
.btn-choose{
	background: #f7f7f7;
    color: #212129;
}
.addfile{
	background: #0077c5 !important;
    color: #fff !important;
}
</style>
<div class="card">
	<div class="card-content collapse show">
		<form id='add_client' action="<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'edit')); ?>" enctype="multipart/form-data" dojoType="dijit.form.Form" method="post">
			<script type="dojo/method" event="onSubmit">			
				if(this.validate()) {
				 	category = dijit.byId('category').get('value')
				  	if(category==0 || category==-1){
						alert('<?php echo $tr->translate("PLEASE_SELECT_CATEGORY");?>');
						dijit.byId('category').focus();
						return false;
			 	   	}
				 	zone_id = dijit.byId('zone_id').get('value')
				  	if(zone_id==0 || zone_id==-1){
						alert('<?php echo $tr->translate("PLEASE_SELECT_ZOZE");?>');
						dijit.byId('zone_id').focus();
						return false;
			 	   	}
					if(dijit.byId('province').get('value')==0){
						alert('<?php echo $tr->translate("PLEASE_SELECT_PROVINCE");?>');
						dijit.byId('province').focus();
						return false;
			 	   }
					loadingBlock();
					return true;
				} else {
					return false;
				}
			</script>
			<div class="card-box">
               	<div class="col-sm-12 border-botom">
		    		<div class="col-sm-8 pd-0">
		    			<h4 class="m-b-0"><i class="fa fa-edit" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('EDIT_CLIENT');?></h4>
	    			</div>
	    			<div class="col-sm-4 text-right">
	    			</div>
	    		</div>
	    	</div>
	    	<div class="card-box">
	    		 <ul class="nav  md-pills pills-primary nav-tab" role="tablist">
		            <li class="nav-item active">
		                <a class="nav-link " data-toggle="tab" href="#panel21" role="tab"><i class="fa fa-user ml-2"></i> <?php echo $tr->translate("CUSTOMER_INFO");?></a>
		            </li>
		            <li class="nav-item">
		                <a class="nav-link" data-toggle="tab" href="#document" role="tab">
		                <i class="fa fa-book ml-2"></i> <?php echo $tr->translate("DOCUMENT");?>
		                </a>
		            </li>
		            <li class="nav-item">
		                <a class="nav-link" data-toggle="tab" href="#panel22" role="tab">
		                <i class="fa fa-users ml-2"></i> <?php echo $tr->translate("MOVING_HISTORY");?>
		                </a>
		            </li>
		        </ul>
		    </div>
		    <div class="col-md-12">
		        <!-- Tab panels -->
		        <div class="tab-content vertical">
			        <!--Panel 1-->
			        <div class="tab-pane fade in active" id="panel21" role="tabpanel">
			        	<div class="col-md-4 col-sm-4 col-xs-12">
							<div class="form-group">
			                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" for="first-name"><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("CUSTOMER_INFO");?> 
			                   </label>
			                </div>
			                <div class="form-group">
			                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("CLIENT_NUM");?> :
			                   </label>
			                   <div class="col-md-7 col-sm-7 col-xs-12">
			                    	<?php echo $frm->getElement('client_number');?>
			                    	<?php echo $frm->getElement('id');?>
			                   </div>
			                </div>
			                <div class="form-group">
			                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("CATEGORY");?>  :
			                   </label>
			                   <div class="col-md-7 col-sm-7 col-xs-12">
			                    	<?php echo $frm->getElement('category');?>
			                   </div>
			                </div>
			                <div class="form-group">
			                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("ORDERING");?>  :
			                   </label>
			                   <div class="col-md-7 col-sm-7 col-xs-12">
			                    	<?php  echo $frm->getElement('ordering');?>
			                   </div>
			                </div>
			                <div class="form-group">
			                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("KH_NAME");?>  :
			                   </label>
			                   <div class="col-md-7 col-sm-7 col-xs-12">
			                    	<?php echo $frm->getElement('name_kh');?>
			                   </div>
			                </div>
			                <div class="form-group">
			                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("EN_NAME");?>  :
			                   </label>
			                   <div class="col-md-7 col-sm-7 col-xs-12">
			                    	<?php echo $frm->getElement('name_en');?>
			                   </div>
			                </div>
			                
			                <div class="form-group">
			                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("SERVICE");?>  :
			                   </label>
			                   <div class="col-md-7 col-sm-7 col-xs-12">
			                    	<?php  echo $frm->getElement('service_id');?>
			                   </div>
			                </div>
			                <div class="form-group">
			                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("PRODUCT");?>  :
			                   </label>
			                   <div class="col-md-7 col-sm-7 col-xs-12">
			                    	<?php  echo $frm->getElement('product_id');?>
			                   </div>
			                </div>
			                <div class="form-group">
			                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("STANDARD");?>  :
			                   </label>
			                   <div class="col-md-7 col-sm-7 col-xs-12">
			                    	<?php  echo $frm->getElement('standard');?>
			                   </div>
			                </div>
			                <div class="form-group">
			                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("MADE_BY");?>  :
			                   </label>
			                   <div class="col-md-7 col-sm-7 col-xs-12">
			                    	<?php  echo $frm->getElement('made_by');?>
			                   </div>
			                </div>
			               
			           	</div>
			        	<div class="col-md-4 col-sm-4 col-xs-12">
							<div class="form-group">
			                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" for="first-name"><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("CONTACT_INFO");?> 
			                   </label>
			                </div>
			                <div class="form-group">
			                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("CONTACT");?>  :
			                   </label>
			                   <div class="col-md-7 col-sm-7 col-xs-12">
			                    	<?php  echo $frm->getElement('contact');?>
			                   </div>
			                </div>
			                <div class="form-group">
			                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("ZONE");?>  :
			                   </label>
			                   <div class="col-md-7 col-sm-7 col-xs-12">
			                    	<?php  echo $frm->getElement('zone_id');?>
			                   </div>
			                </div>
			                <div class="form-group">
			                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("STREET");?>  :
			                   </label>
			                   <div class="col-md-7 col-sm-7 col-xs-12">
			                    	<?php  echo $frm->getElement('street_id');?>
			                   </div>
			                </div>
			                <div class="form-group">
			                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("LINE");?>  :
			                   </label>
			                   <div class="col-md-7 col-sm-7 col-xs-12">
			                    	<?php  echo $frm->getElement('line');?>
			                   </div>
			                </div>
			                <div class="form-group">
			                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("FLOOR");?>  :
			                   </label>
			                   <div class="col-md-7 col-sm-7 col-xs-12">
			                    	<?php  echo $frm->getElement('floor');?>
			                   </div>
			                </div>
			                <div class="form-group">
			                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("PROVINCE");?>  :
			                   </label>
			                   <div class="col-md-7 col-sm-7 col-xs-12">
			                    	<?php echo $frm->getElement('province');?>
			                   </div>
			                </div>
			                <div class="form-group">
			                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("DISTRICT");?> :
			                   </label>
			                   <div class="col-md-7 col-sm-7 col-xs-12">
			                    	<input id="district" required="true" >
			                   </div>
			                </div>
			                <div class="form-group">
			                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("COMMUNE");?>  :
			                   </label>
			                   <div class="col-md-7 col-sm-7 col-xs-12">
			                    	<input id="commune" >
			                   </div>
			                </div>
			                <div class="form-group">
			                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("VILLAGE");?>  :
			                   </label>
			                   <div class="col-md-7 col-sm-7 col-xs-12">
			                    	<input id="village" >
			                   </div>
			                </div>
			                <div class="form-group">
			                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("MAP");?> :
			                   </label>
			                   <div class="col-md-7 col-sm-7 col-xs-12">
			                    	<?php  echo $frm->getElement('map');?>
			                   </div>
			                </div>
			            </div>
			            <div class="col-md-4 col-sm-4 col-xs-12">
							<div class="form-group">
			                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" for="first-name"><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("OTHER_INFO");?> 
			                   </label>
			                </div>
			                <div class="form-group">
			                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name">
			                   </label>
			                   <div class="col-md-7 col-sm-7 col-xs-12">
			                    	<?php 
									$images = $this->baseUrl().'/images/no-photo.png';
									if (!empty($this->row['photo_name'])){
										if (file_exists(PUBLIC_PATH."/images/photo/".$this->row['photo_name'])){
											$images = $this->baseUrl()."/images/photo/".$this->row['photo_name'];
										}
									}
									?>
									<input name="old_photo"  value="<?php echo $this->photo;?>" type="hidden" />
									<div class="account-image" >
										<div class="image-box">
											<img id="profile_wiew" src="<?php echo $images;?>" alt=""  />
										</div>
										<div class="button_browse">
										<div id='preview'></div>	
											<span>Upload <span ><i class="fa fa-camera" aria-hidden="true"></i></span></span>
											<input class="btn_borwse_image" type="file" id="photo" name="photo" />
										</div>
									</div>
			                   </div>
			                </div>
			                <div class="form-group">
			                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("SIDE");?>  :
			                   </label>
			                   <div class="col-md-7 col-sm-7 col-xs-12">
			                    	<?php  echo $frm->getElement('side');?>
			                   </div>
			                </div>
			                <div class="form-group">
			                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("START_DIRECTION");?>  :
			                   </label>
			                   <div class="col-md-7 col-sm-7 col-xs-12">
			                    	<?php  echo $frm->getElement('start_direction');?>
			                   </div>
			                </div>
			                <div class="form-group">
			                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("VERIFICATION");?>  :
			                   </label>
			                   <div class="col-md-7 col-sm-7 col-xs-12">
			                    	<?php  echo $frm->getElement('verification_note');?>
			                   </div>
			                </div>
			                <div class="form-group">
			                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("OTHER");?>  :
			                   </label>
			                   <div class="col-md-7 col-sm-7 col-xs-12">
			                    	<?php  echo $frm->getElement('other');?>
			                   </div>
			                </div>
			                 <div class="form-group">
			                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("NOTE");?> :
			                   </label>
			                   <div class="col-md-7 col-sm-7 col-xs-12">
			                    	<?php  echo $frm->getElement('noted');?>
			                   </div>
			                </div>
			                <div class="form-group">
			                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("STATUS");?>  :
			                   </label>
			                   <div class="col-md-7 col-sm-7 col-xs-12">
			                    	<?php  echo $frm->getElement('status');?>
			                   </div>
			                </div>
			            </div>
			        </div>
			        <!--/.Panel 1-->
			        
			        <div class="tab-pane fade in " id="document" role="tabpanel">
			        	<div class="col-md-8 col-sm-8 col-xs-12">
			         		<div class="form-group">
				         	 	 <div class="col-md-10 col-sm-10 col-xs-10" id="fileList"></div>
				         	 </div>
				         	 <div class="form-group">
				         	 	<button class="btn btn-default addfile" onclick="addRow();" type="button"><?php echo $tr->translate('Add More Doc')?></button>
								<input type="hidden" name="identity" id="identity"  value="" >
				         	 </div>
			         	</div>
			        </div>
			        
			         <!--Panel 2-->
			        <div class="tab-pane fade in " id="panel22" role="tabpanel">
			        	<div class="form-group">
			        		<table class="history-record" >
		                		<thead>
		                			<tr>
		                				<th><?php echo $tr->translate("NUM");?></th>
		                				<th><?php echo $tr->translate("MOVE_FROM");?></th>
		                				<th><?php echo $tr->translate("MOVE_TO");?></th>
		                				<th><?php echo $tr->translate("NOTE");?></th>
		                				<th></th>
		                			</tr>
		                		</thead>
		                		<tbody>
		                			<?php if (!empty($this->movinghist)) foreach ($this->movinghist as $key => $rs){?>
		                			<tr>
		                				<td align="center"><?php echo $key+1;?></td>
		                				<td>
		                					<?php echo $tr->translate("ZONE")." : ".$rs['zone'];
		                						echo empty($rs['street'])?"":", ".$tr->translate("STREET")." : ".$rs['street'];
		                						echo empty($rs['line'])?"":", ".$tr->translate("LINE")." : ".$rs['line'];
		                						echo empty($rs['floor'])?"":", ".$tr->translate("FLOOR")." : ".$rs['floor'];
		                						echo empty($rs['side'])?"":", ".$tr->translate("SIDE")." : ".$rs['side'];
		                						echo empty($rs['start_direction'])?"":", ".$tr->translate("START_DIRECTION")." : ".$rs['start_direction'];
		                						echo "<br />";
		                						echo empty($rs['province'])?"":"".$tr->translate("PROVINCE")." : ".$rs['province'];
		                						echo empty($rs['district'])?"":", ".$tr->translate("DISTRICT")." : ".$rs['district'];
		                						echo empty($rs['commnune'])?"":", ".$tr->translate("COMMUNE")." : ".$rs['commnune'];
		                						echo empty($rs['village_name'])?"":", ".$tr->translate("VILLAGE")." : ".$rs['village_name'];
		                					?>
		                				</td>
		                				<td>
		                					<?php echo $tr->translate("ZONE")." : ".$rs['new_zone'];
		                						echo empty($rs['new_street'])?"":", ".$tr->translate("STREET")." : ".$rs['new_street'];
		                						echo empty($rs['new_line'])?"":", ".$tr->translate("LINE")." : ".$rs['new_line'];
		                						echo empty($rs['new_floor'])?"":", ".$tr->translate("FLOOR")." : ".$rs['new_floor'];
		                						echo empty($rs['new_side'])?"":", ".$tr->translate("SIDE")." : ".$rs['new_side'];
		                						echo empty($rs['new_start_direction'])?"":", ".$tr->translate("START_DIRECTION")." : ".$rs['new_start_direction'];
		                						echo "<br />";
		                						echo empty($rs['new_province'])?"":"".$tr->translate("PROVINCE")." : ".$rs['new_province'];
		                						echo empty($rs['new_district'])?"":", ".$tr->translate("DISTRICT")." : ".$rs['new_district'];
		                						echo empty($rs['new_commnune'])?"":", ".$tr->translate("COMMUNE")." : ".$rs['new_commnune'];
		                						echo empty($rs['new_village_name'])?"":", ".$tr->translate("VILLAGE")." : ".$rs['new_village_name'];
		                					?>
		                				</td>
		                				<td><?php echo $rs['note'];?></td>
		                			</tr>
		                			<?php }?>
		                		</tbody>
		             		</table>
			             </div>
			        </div>
			        <!--/.Panel 2-->
			    </div>
			</div>
			<div class="clearfix"></div>
			    <div class="card-box">
               		<div class="col-sm-12 border-top mt-20 ptb-10 text-center">
						<input type="submit" value="SAVE_NEW" tabindex="1" label="<?php echo $tr->translate('GO_EDIT');?>" id="save_new" dojoType="dijit.form.Button" name="save_new"
							iconClass="dijitEditorIcon dijitEditorIconSave"/>
	    		</div>
	    	</div>
		</form>
	</div>
</div>
<style>
table.history-record {
    width: 100%;
    font-size: 12px;
}
table.history-record thead tr th {
    text-align: center;
    padding: 5px 2px;
    background: #e0eafb;
    border-bottom: solid 1px #afadad;
	    border: solid 1px #ccc;
}
table.history-record tbody tr {
    border-bottom: solid 1px #e8e8e8;
}
table.history-record tbody tr td {
    padding: 5px;
	vertical-align: top;
}
a.btn.btn-primary.btn-xs {
    margin-bottom: -2px;
    padding: 1px 5px;
    background: #02014a;
    border: solid 1px #3d3c7d;
}  
</style>
<?php 
	echo $this->frm_popup_district;
	echo $this->frm_popup_village;
	echo $this->frm_popup_comm;
	echo $this->frm_popupOther;
	
	echo $this->frmPopupService;
	echo $this->frmPopupProduct;
	echo $this->frmPopupStandard;
	echo $this->frmPopupMadeBy;
	echo $this->frmPopupStreet;
	echo $this->frmPopupZone;
	echo $this->frmPopupCate;
?>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script>
	dojo.require("dojo.data.ItemFileWriteStore");  
	dojo.require("dijit.form.DateTextBox");
	dojo.require("dijit.Dialog");
	dojo.require("dijit.form.Textarea");
	dojo.require("dijit.form.NumberTextBox");
</script>
<script type="text/javascript">
var other_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->other));?> );
var floor_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->floor));?> );
var line_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->line));?> );
var side_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->side));?> );
var start_direction_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->start_direction));?> );
var verification_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->verification));?> );
require(["dojo/ready"], function(ready){
	new dijit.form.FilteringSelect({
		name: "other",
		id: "other",
		autoComplete: false,
		queryExpr: "*${0}*",     
		searchAttr: "name",
		class: 'fullside',
		onChange: function() {
			popupFormData(1);
	    }
	}, "other");
	new dijit.form.FilteringSelect({
		name: "floor",
		id: "floor",
		autoComplete: false,
		queryExpr: "*${0}*",     
		searchAttr: "name",
		class: 'fullside',
		onChange: function() {
			popupFormData(2);
	    }
	}, "floor");
	new dijit.form.FilteringSelect({
		name: "line",
		id: "line",
		autoComplete: false,
		queryExpr: "*${0}*",     
		searchAttr: "name",
		class: 'fullside',
		onChange: function() {
			popupFormData(3);
	    }
	}, "line");
	new dijit.form.FilteringSelect({
		name: "side",
		id: "side",
		autoComplete: false,
		queryExpr: "*${0}*",     
		searchAttr: "name",
		class: 'fullside',
		onChange: function() {
			popupFormData(4);
	    }
	}, "side");
	new dijit.form.FilteringSelect({
		name: "start_direction",
		id: "start_direction",
		autoComplete: false,
		queryExpr: "*${0}*",     
		searchAttr: "name",
		class: 'fullside',
		onChange: function() {
			popupFormData(5);
	    }
	}, "start_direction");
	new dijit.form.FilteringSelect({
		name: "verification",
		id: "verification",
		autoComplete: false,
		queryExpr: "*${0}*",     
		searchAttr: "name",
		class: 'fullside',
		onChange: function() {
			popupFormData(6);
	    }
	}, "verification");

	new dijit.form.FilteringSelect({
		name: "service_id",
		id: "service_id",
		autoComplete: false,
		queryExpr: "*${0}*",     
		searchAttr: "name",
		class: 'fullside',
		onChange: function() {
			popupFormDataCate(1);
	    }
	}, "service_id");

	new dijit.form.FilteringSelect({
		name: "product_id",
		id: "product_id",
		autoComplete: false,
		queryExpr: "*${0}*",     
		searchAttr: "name",
		class: 'fullside',
		onChange: function() {
			popupFormDataCate(2);
	    }
	}, "product_id");

	new dijit.form.FilteringSelect({
		name: "standard",
		id: "standard",
		autoComplete: false,
		queryExpr: "*${0}*",     
		searchAttr: "name",
		class: 'fullside',
		onChange: function() {
			popupFormDataCate(3);
	    }
	}, "standard");

	new dijit.form.FilteringSelect({
		name: "made_by",
		id: "made_by",
		autoComplete: false,
		queryExpr: "*${0}*",     
		searchAttr: "name",
		class: 'fullside',
		onChange: function() {
			popupFormDataCate(4);
	    }
	}, "made_by");

	new dijit.form.FilteringSelect({
		name: "street_id",
		id: "street_id",
		autoComplete: false,
		queryExpr: "*${0}*",     
		searchAttr: "name",
		class: 'fullside',
		onChange: function() {
			popupFormDataCate(5);
	    }
	}, "street_id");

	new dijit.form.FilteringSelect({
		name: "zone_id",
		id: "zone_id",
		autoComplete: false,
		queryExpr: "*${0}*",     
		searchAttr: "name",
		class: 'fullside',
		onChange: function() {
			popupFormDataCate(6);
	    }
	}, "zone_id");

	new dijit.form.FilteringSelect({
		name: "category",
		id: "category",
		autoComplete: false,
		queryExpr: "*${0}*",     
		searchAttr: "name",
		class: 'fullside',
		onChange: function() {
			popupCategory();
	    }
	}, "category");
});
function popupFormDataCate(index){
	if(index==1){
		service_id = dijit.byId('service_id').get('value');
		if(service_id==-1){
			dijit.byId("frm_datapop_service").show();
		}
	}else if(index==2){
		product_id = dijit.byId('product_id').get('value');
		if(product_id==-1){
			dijit.byId("frm_datapop_product").show();
		}
	}else if(index==3){
		standard = dijit.byId('standard').get('value');
		if(standard==-1){
			dijit.byId("frm_datapop_standard").show();
		}
	}else if(index==4){	
		made_by = dijit.byId('made_by').get('value');
		if(made_by==-1){
			dijit.byId("frm_datapop_madeby").show();
		}
	}else if(index==5){
		street_id = dijit.byId('street_id').get('value');
		if(street_id==-1){
			dijit.byId("frm_datapop_street").show();
		}
	}else if(index==6){
		zone_id = dijit.byId('zone_id').get('value');
		if(zone_id==-1){
			dijit.byId("frm_datapop_zone").show();
		}
	}
}
var service_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->service));?> );
function addService(){
	var url_ajax = '<?php echo $this->url(array('module'=>'group','controller'=>'service','action'=>'addajax')); ?>';
	if(dijit.byId('form_popup_service').validate()){
		loadingBlock();
		dojo.xhrPost({
			url: url_ajax,
			form: dojo.byId("form_popup_service"),
			handleAs:"json",
			load: function(data) {
				var Itemmake = {					
						id: data,
						name: dijit.byId('title_service').get('value')
				};
				addDataToSelectbox(dijit.byId('service_id'),service_store , Itemmake, data);
				dijit.byId('form_popup_service').reset();
				dijit.byId("frm_datapop_service").hide();
				HideloadingBlock();
			},
			error: function(err) {
				HideloadingBlock();
			}
		});
	}
}
var product_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->product));?> );
function addProduct(){
	var url_ajax = '<?php echo $this->url(array('module'=>'group','controller'=>'product','action'=>'addajax')); ?>';
	if(dijit.byId('form_popup_product').validate()){
		loadingBlock();
		dojo.xhrPost({
			url: url_ajax,
			form: dojo.byId("form_popup_product"),
			handleAs:"json",
			load: function(data) {
				var Itemmake = {					
						id: data,
						name: dijit.byId('title_product').get('value')
				};
				addDataToSelectbox(dijit.byId('product_id'),product_store , Itemmake, data);
				dijit.byId('form_popup_product').reset();
				dijit.byId("frm_datapop_product").hide();
				HideloadingBlock();
			},
			error: function(err) {
				HideloadingBlock();
			}
		});
	}
}
var standard_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->standard));?> );
function addStandard(){
	var url_ajax = '<?php echo $this->url(array('module'=>'group','controller'=>'standard','action'=>'addajax')); ?>';
	if(dijit.byId('form_popup_standard').validate()){
		loadingBlock();
		dojo.xhrPost({
			url: url_ajax,
			form: dojo.byId("form_popup_standard"),
			handleAs:"json",
			load: function(data) {
				var Itemmake = {					
						id: data,
						name: dijit.byId('title_standard').get('value')
				};
				addDataToSelectbox(dijit.byId('standard'),standard_store , Itemmake, data);
				dijit.byId('form_popup_standard').reset();
				dijit.byId("frm_datapop_standard").hide();
				HideloadingBlock();
			},
			error: function(err) {
				HideloadingBlock();
			}
		});
	}
}
var madeby_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->madeby));?> );
function addMadeBy(){
	var url_ajax = '<?php echo $this->url(array('module'=>'group','controller'=>'madeby','action'=>'addajax')); ?>';
	if(dijit.byId('form_popup_madeby').validate()){
		loadingBlock();
		dojo.xhrPost({
			url: url_ajax,
			form: dojo.byId("form_popup_madeby"),
			handleAs:"json",
			load: function(data) {
				var Itemmake = {					
						id: data,
						name: dijit.byId('title_madeby').get('value')
				};
				addDataToSelectbox(dijit.byId('standard'),madeby_store , Itemmake, data);
				dijit.byId('form_popup_madeby').reset();
				dijit.byId("frm_datapop_madeby").hide();
				HideloadingBlock();
			},
			error: function(err) {
				HideloadingBlock();
			}
		});
	}
}
var street_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->street));?> );
function addStreetd(){
	var url_ajax = '<?php echo $this->url(array('module'=>'other','controller'=>'street','action'=>'addajax')); ?>';
	if(dijit.byId('form_popup_street').validate()){
		loadingBlock();
		dojo.xhrPost({
			url: url_ajax,
			form: dojo.byId("form_popup_street"),
			handleAs:"json",
			load: function(data) {
				var Itemmake = {					
						id: data,
						name: dijit.byId('str_no').get('value')+' - '+dijit.byId('str_title').get('value')
				};
				addDataToSelectbox(dijit.byId('street_id'),street_store , Itemmake, data);
				dijit.byId('form_popup_street').reset();
				dijit.byId("frm_datapop_street").hide();
				HideloadingBlock();
			},
			error: function(err) {
				HideloadingBlock();
			}
		});
	}
}
var zone_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->zone));?> );
function addZone(){
	var url_ajax = '<?php echo $this->url(array('module'=>'other','controller'=>'zone','action'=>'addajax')); ?>';
	if(dijit.byId('form_popup_zone').validate()){
		loadingBlock();
		dojo.xhrPost({
			url: url_ajax,
			form: dojo.byId("form_popup_zone"),
			handleAs:"json",
			load: function(data) {
				var Itemmake = {					
						id: data,
						name: dijit.byId('title_zone').get('value')
				};
				addDataToSelectbox(dijit.byId('zone_id'),zone_store , Itemmake, data);
				dijit.byId('form_popup_zone').reset();
				dijit.byId("frm_datapop_zone").hide();
				HideloadingBlock();
			},
			error: function(err) {
				HideloadingBlock();
			}
		});
	}
}
function popupFormData(index){
	dijit.byId('type').set('value',index);
	if(index==1){
		controlvalue = dijit.byId('other').get('value');
		$("#title_form").html("<?php echo $tr->translate("ADD_OTHER");?>");
	}else if(index==2){
		controlvalue = dijit.byId('floor').get('value');
		$("#title_form").html("<?php echo $tr->translate("ADD_FLOOR");?>");
	}else if(index==3){
		controlvalue = dijit.byId('line').get('value');
		$("#title_form").html("<?php echo $tr->translate("ADD_LINE");?>");
	}else if(index==4){
		controlvalue = dijit.byId('side').get('value');
		$("#title_form").html("<?php echo $tr->translate("ADD_SIDE");?>");
	}else if(index==5){
		controlvalue = dijit.byId('start_direction').get('value');
		$("#title_form").html("<?php echo $tr->translate("ADD_START_DIRECTION");?>");
	}else if(index==6){
		controlvalue = dijit.byId('verification').get('value');
		$("#title_form").html("<?php echo $tr->translate("ADD_VERIFICATION");?>");
	}
	if(controlvalue==-1){
		dijit.byId("frm_datapop").show();
	}
}
var url_branch = '<?php echo $this->url(array('module'=>'other','controller'=>'index','action'=>'addnewdata')); ?>';
function addData(){
	if(dijit.byId('form_popup').validate()){
		loadingBlock();
		dojo.xhrPost({
			url:url_branch,
			form: dojo.byId("form_popup"),
			handleAs:"json",
			load: function(data) {
				var Itemmake = {					
						id: data,
						name: dijit.byId('title').get('value')
				};
				var type = dijit.byId('type').get('value');	
				if(type==1){
					addDataToSelectbox(dijit.byId('other'),other_store , Itemmake, data);
				}else if(type==2){
					addDataToSelectbox(dijit.byId('floor'),floor_store , Itemmake, data);
				}else if(type==3){
					addDataToSelectbox(dijit.byId('line'),line_store , Itemmake, data);
				}else if(type==4){
					addDataToSelectbox(dijit.byId('side'),side_store , Itemmake, data);
				}else if(type==5){
					addDataToSelectbox(dijit.byId('start_direction'),start_direction_store , Itemmake, data);
				}else if(type==6){
					addDataToSelectbox(dijit.byId('verification'),verification_store , Itemmake, data);
				}	
				dijit.byId('form_popup').reset();
				dijit.byId("frm_datapop").hide();
				HideloadingBlock();
			},
			error: function(err) {
				HideloadingBlock();
			}
		});
	}
}
function popupCategory(){
	category= dijit.byId('category').get('value')
	if(category==-1){
		dijit.byId("frm_datapop_category").show();
	}
}
function addCategory(){
	var url_ajax = '<?php echo $this->url(array('module'=>'group','controller'=>'category','action'=>'addajax')); ?>';
	if(dijit.byId('form_popup_category').validate()){
		loadingBlock();
		dojo.xhrPost({
			url: url_ajax,
			form: dojo.byId("form_popup_category"),
			handleAs:"json",
			load: function(data) {
				category_store  = getDataStorefromJSON('id','name', data.datastore);		
			    dijit.byId('category').set('store', category_store);
			    dijit.byId('category').set('value', data.id);
				dijit.byId('form_popup_category').reset();
				dijit.byId("frm_datapop_category").hide();
				HideloadingBlock();
			},
			error: function(err) {
				HideloadingBlock();
				//alert(err);
			}
		});
	}
}
function readURL(input) {
    if (input.files && input.files[0]) {
        var reader = new FileReader();
        
        reader.onload = function (e) {
            $('#profile_wiew').attr('src', e.target.result);
        }
        reader.readAsDataURL(input.files[0]);
    }
}
$("#photo").change(function(){
    readURL(this);
});

var district_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?> );
var commune_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?> );
var village_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?> );


dojo.ready(function(){
	try{

	new dijit.form.FilteringSelect({
	store: district_store,
	autoComplete:false,
	queryExpr:'*${0}*',
	required: false,		           
	name: "district",
	id: "district",
	value: "",
	searchAttr: "name",
	class: 'fullside',
		onChange: function() {
			district = dijit.byId('district').get('value');
			if(district==-1){
				showPopupdistrict();
				}
				filterCommune();
		}  
	}, "district");
	 
	new dijit.form.FilteringSelect({
	store: commune,
	autoComplete:false,
	queryExpr:'*${0}*',
	required: false,		           
	name: "commune",
	id: "commune",
	searchAttr: "name",
	class: 'fullside',
	onChange: function() {
			commune = dijit.byId('commune').get('value');
			if(commune==-1){
				showPopupCommune();
			}
			else{
				filterVillage();
			}
   	}
   }, "commune");
	new dijit.form.FilteringSelect({
	store: village_store,
	autoComplete:false,
	queryExpr:'*${0}*',
	required: false,		           
	name: "village",
	id: "village",
	searchAttr: "name",
	class: 'fullside',
		onChange: function() {
			vill = dijit.byId('village').get('value');
			if(vill==-1){
				showPopupVillage();
			}
		}
	}, "village");

		
		filterDistrict();
		filterCommune();
		filterVillage();
	}catch(e){
	}
	initialize();
});
var col = 0;
var no = 0;
func='';
tmp = '';
var temp='';
function addRow() {
		col++;no++;
		template='';
			template+='<div id="attachment'+col+'" class="form-group" style=" margin-bottom: 5px !important;">';
				template+='<div class="input-group input-file" name="attachment'+col+'">';
	 				template+='<span class="input-group-btn">';
	 				template+='<button class="btn btn-default btn-choose" type="button"><?php echo $tr->translate('CHOOSE_FILE');?></button>';
	 				template+='</span>';
					template+='<input type="text" class="form-control" placeholder="<?php echo $tr->translate('CHOOSE_FILE');?>..." />';
					template+='<span class="input-group-btn">';
					template+='<button title="<?php echo $tr->translate('DELETE');?>" onClick="deleteRecord('+col+');" class="btn btn-error btn-reset" type="button"><i class="fa fa-trash-o" aria-hidden="true"></i></button>';
					template+='</span>';
				template+='</div>';
			template+='</div> <div class="clearfix"></div>';
		$("#fileList").append(template);		
		if($("#identity").val()!='') {
			var identity = $("#identity").val();
			$("#identity").val(identity+','+col);
		} else {$("#identity").val(col);}
		bs_input_file();
}
function initialize(){
    <?php if (!empty($this->document)) foreach ($this->document as $rs){?>
	    col++;no++;
		template='';
			template+='<div id="attachment'+col+'" class="form-group"  style=" margin-bottom: 5px !important;">';
				template+='<div  class=" input-group input-file foredit" name="attachment'+col+'">';
	 				template+='<span class="input-group-btn">';
	 					template+='<button class="btn btn-default btn-choose" type="button"><?php echo $tr->translate('CHOOSE_FILE');?></button>';
	 					template+='</span>';
						template+='<input type="text" class="form-control" placeholder="<?php echo $tr->translate('CHOOSE_FILE');?>..." value="<?php echo $rs['document_name'];?>"/>';
						template+='<span class="input-group-btn">';
						template+='<button title="<?php echo $tr->translate('DELETE');?>" onClick="deleteRecord('+col+');" class="btn btn-error btn-reset" type="button"><i class="fa fa-trash-o" aria-hidden="true"></i></button>';
						template+='<a title="<?php echo $tr->translate('VIEW_DOCUMENT');?>" href="<?php echo $this->baseUrl()."/images/document/".$rs['document_name'];?>" target="_blank" class="btn btn-error btn-reset" ><i class="fa fa-eye" aria-hidden="true"></i></button></a>';
					template+='</span>';
					template+='<input type="hidden" id="detailid'+col+'" name="detailid'+col+'"  value="<?php echo $rs['id'];?>" />';
				template+='</div>';
				template+='<input type="hidden" id="old_file'+col+'" name="old_file'+col+'"  value="<?php echo $rs['document_name'];?>" />';
				template+='<div class="clearfix"></div>';
			template+='</div>';
			$("#fileList").append(template);
		if($("#identity").val()!='') {
			var identity = $("#identity").val();
			$("#identity").val(identity+','+col);
		} else {$("#identity").val(col);}
		bs_input_file();
		<?php }?>
}
function bs_input_file() {
		$(".input-file").before(
			function(){
			if ( ! $(this).prev().hasClass('input-ghost') ) {
				var element = $("<input  type='file' accept='.xlsx,.xls,image/*,.doc, .docx,.txt,.pdf' class='input-ghost' style='visibility:hidden; height:0'>");
				element.attr("name",$(this).attr("name"));
				element.change(function(){
					element.next(element).find('input').val((element.val()).split('\\').pop());
				});
				$(this).find("button.btn-choose").click(function(){
					element.click();
				});
				
				$(this).find('input').css("cursor","pointer");
				$(this).find('input').mousedown(function() {
					$(this).parents('.input-file').prev().click();
					return false;
				});
				return element;
			}
		}
		);
	}
	function deleteRecord(index){
		var identity = $('#identity').val();
		var arrays = identity.split(',');
		for(var i=0;i<arrays.length;i++) {
		if(arrays[i] == index) arrays.splice(i,1);
		}
		var strings = arrays.join(',');
		$('#identity').val(strings);
		$("#attachment"+index).remove();
		bs_input_file();
	}
	$(function(){
		bs_input_file();
	});
	
url_getdistrict = '<?php echo $this->url(array('module'=>'other','controller'=>'district','action'=>'get-district'));?>';
function filterDistrict(){
	pro_id = dijit.byId('province').get('value');
	if(pro_id==0){
		return false;
	}
	dojo.xhrPost({
		url:url_getdistrict,	
		content:{ 
			'pro_id': pro_id
		},
		handleAs:"json",
		load: function(data) {	
			dijit.byId('district').reset('value');
			district_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('district').set('store', district_store);
		    if(pro_id=='<?php echo $this->row['pro_id'];?>'){
		    	dijit.byId('district').attr('value',<?php echo $this->row['dis_id'];?>);
		    }
		},
		error: function(err) {
		}
	});	
}
url_getcommune = '<?php echo $this->url(array('module'=>'other','controller'=>'commune','action'=>'get-commune'));?>';
function filterCommune(){
	distict_id = dijit.byId('district').get('value');
	if(distict_id==0){
		return false;}
		dojo.xhrPost({
			url:url_getcommune,	
			content:{ 
				'district_id': distict_id
			},
			handleAs:"json",
			load: function(data) {	
				commune_store  = getDataStorefromJSON('id','name', data);		
			    dijit.byId('commune').set('store', commune_store);
			    if(distict_id=='<?php echo $this->row['dis_id'];?>'){
			    	dijit.byId('commune').attr('value',<?php echo $this->row['com_id'];?>);
			    }
			},
			error: function(err) {
			}
		});
}
url_getvillage = '<?php echo $this->url(array('module'=>'other','controller'=>'village','action'=>'get-allvillage'));?>';
function filterVillage(){
	commune_id = dijit.byId('commune').get('value');
	if(commune_id==0){
		return false;}
		dojo.xhrPost({
			url:url_getvillage,	
			content:{ 
				'commune_id': commune_id
			},
			handleAs:"json",
			load: function(data) {	
				village_store  = getDataStorefromJSON('id','name', data);		
			    dijit.byId('village').set('store', village_store);
			    if(commune_id=='<?php echo $this->row['com_id'];?>'){
			    	dijit.byId('village').attr('value',<?php echo $this->row['village_id'];?>);
			    }
			},
			error: function(err) {
			}
		});
}
client_village = '<?php echo $this->url(array('module'=>'other','controller'=>'village','action'=>'add-village'));?>';
function addVillage(){
	if(dijit.byId('frm_village').validate()) {
		loadingBlock();
		dojo.xhrPost({
			url:client_village,	
			form:dojo.byId('form_village'),
			handleAs:"json",
			load: function(data) {
				labelen = dijit.byId('village_name').get('value');
				labelkh = dijit.byId('village_namekh').get('value');
				var villageItem1 = {					
						id: data,
						name: labelen+' - '+labelkh,
				};			
				addDataToSelectbox(dijit.byId('village'), village_store, villageItem1, data);	
				dijit.byId('frm_village').reset();
				dijit.byId('frm_village').hide();
				HideloadingBlock();
			},
			error: function(err){
			}
		});
	}
}
function showPopupVillage(){
	communeid = dijit.byId('commune').get('value');
	if(communeid!=-1){
		province_id = dijit.byId('province').get('value');
		dijit.byId('province_name').attr('value',province_id);
		dijit.byId('province_name').set('readOnly',true);

		district_name=province_id = dijit.byId('district').get('value');
		dijit.byId('district_name').attr('value',district_name);
		dijit.byId('district_name').set('readOnly',true);

		dijit.byId('commune_name').attr('value',communeid);
		dijit.byId('commune_name').set('readOnly',true);
		dijit.byId('frm_village').show();
	}else{
		alert('please select commune first');
		dijit.byId('commune').focus();
	}
}
function showPopupCommune(){
	district = dijit.byId('district').get('value');
	if(district!=-1){
		dijit.byId('district_nameen').attr('value',district);
		dijit.byId('district_nameen').set('readOnly',true);
		dijit.byId('frm_commune').show();
	}else{
		alert('please select district first');
		dijit.byId('district').focus();
	}
}
function showPopupdistrict(){
	province_id = dijit.byId('cprovince').get('value');
	if(province_id!=0){
		dijit.byId('province_names').attr('value',province_id);
		dijit.byId('province_names').set('readOnly',true);
		dijit.byId('frm_district').show();
	}else{
		alert('please select province first');
		dijit.byId('cprovince').focus();
	}
}
var district_url = '<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'insert-district'));?>';
function addNewDistrict(){
	if(dijit.byId('frm_district').validate()) {
		loadingBlock();
		dojo.xhrPost({
			url:district_url,	
			form:dojo.byId('form_district'),
			handleAs:"json",
			load: function(data) {	
				var myNewItem1 = {					
						id: data,
						name: dijit.byId('pop_district_name').get('value')+' - '+dijit.byId('pop_district_namekh').get('value'),
				};			
				addDataToSelectbox(dijit.byId('district'), district_store, myNewItem1, data);	
				dijit.byId('frm_district').reset();
				dijit.byId('frm_district').hide();
				HideloadingBlock();
			},
			error: function(err) {
			}
		});	
	}
}
var commune_url = '<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'insertcommune'));?>';
function addNewCommune(){
	if(dijit.byId('frm_commune').validate()) {
		loadingBlock();
		dojo.xhrPost({
			url:commune_url,	
			form:dojo.byId('form_commune'),
			handleAs:"json",
			load: function(data) {	
				communeen = dijit.byId('commune_nameen').get('value');
				communekh = dijit.byId('commune_namekh').get('value');
				var Itemcommune = {					
						id: data,
						name: communeen+' - '+communekh,
				};			
				addDataToSelectbox(dijit.byId('commune'), commune_store, Itemcommune, data);
				dijit.byId('frm_commune').reset();
				dijit.byId('frm_commune').hide();
				HideloadingBlock();
			},
			error: function(err) {
			}
		});
	}
}

</script>