<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('MOVING'));
  $frm = $this->frm_client;?>


<div class="card">
	<div class="card-content collapse show">
		<form id='add_client' action="" enctype="multipart/form-data" dojoType="dijit.form.Form" method="post">
			<script type="dojo/method" event="onSubmit">			
				if(this.validate()) {
				 	zone_id = dijit.byId('zone_id').get('value')
				  	if(zone_id==0 || zone_id==-1){
						alert('<?php echo $tr->translate("PLEASE_SELECT_ZOZE");?>');
						dijit.byId('zone_id').focus();
						return false;
			 	   	}

					if(dijit.byId('province').get('value')==0){
						alert('<?php echo $tr->translate("PLEASE_SELECT_PROVINCE");?>');
						dijit.byId('province').focus();
						return false;
			 	   }
					loadingBlock();
					return true;
				} else {
					return false;
				}
			</script>
			<div class="card-box">
               	<div class="col-sm-12 border-botom">
		    		<div class="col-sm-8 pd-0">
		    			<h4 class="m-b-0"><i class="fa fa-random" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('MOVING');?>
		    			(<?php echo $this->row['client_number']." ".$this->row['name_kh']."/".$this->row['name_en']?>)
		    			</h4>
	    			</div>
	    			<div class="col-sm-4 text-right">
	    			</div>
	    		</div>
	    	</div>
	    	<div class="card-box">
	    		 <ul class="nav  md-pills pills-primary nav-tab" role="tablist">
		            <li class="nav-item active">
		                <a class="nav-link " data-toggle="tab" href="#panel21" role="tab"><i class="fa fa-random ml-2"></i> <?php echo $tr->translate("MOVING_INFO");?></a>
		            </li>
		            <li class="nav-item">
		                <a class="nav-link" data-toggle="tab" href="#panel22" role="tab">
		                <i class="fa fa-users ml-2"></i> <?php echo $tr->translate("MOVING_HISTORY");?>
		                </a>
		            </li>
		        </ul>
		    </div>
		    <div class="col-md-12">
		        <!-- Tab panels -->
		        <div class="tab-content vertical">
			        <!--Panel 1-->
			        <div class="tab-pane fade in active" id="panel21" role="tabpanel">
			        	<div class="col-md-4 col-sm-4 col-xs-12">
							<div class="form-group">
			                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" for="first-name"><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("CONTACT_INFO");?> 
			                   </label>
			                </div>
			                <div class="form-group">
			                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("MOVING_DATE");?>  :
			                   </label>
			                   <div class="col-md-7 col-sm-7 col-xs-12">
			                    	<?php  echo $frm->getElement('moving_date');?>
			                   </div>
			                </div>
			                <div class="form-group">
			                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("ZONE");?>  :
			                   </label>
			                   <div class="col-md-7 col-sm-7 col-xs-12">
			                    	<?php  echo $frm->getElement('zone_id');?>
			                    	<input dojoType="dijit.form.ValidationTextBox" required="true" id="client_id" name="client_id" value="<?php echo $this->row['id'];?>" type="hidden" class="fullside">
			                   </div>
			                </div>
			                <div class="form-group">
			                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("STREET");?>  :
			                   </label>
			                   <div class="col-md-7 col-sm-7 col-xs-12">
			                    	<?php  echo $frm->getElement('street_id');?>
			                   </div>
			                </div>
			                <div class="form-group">
			                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("LINE");?>  :
			                   </label>
			                   <div class="col-md-7 col-sm-7 col-xs-12">
			                    	<?php  echo $frm->getElement('line');?>
			                   </div>
			                </div>
			                <div class="form-group">
			                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("FLOOR");?>  :
			                   </label>
			                   <div class="col-md-7 col-sm-7 col-xs-12">
			                    	<?php  echo $frm->getElement('floor');?>
			                   </div>
			                </div>
			                <div class="form-group">
			                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("PROVINCE");?>  :
			                   </label>
			                   <div class="col-md-7 col-sm-7 col-xs-12">
			                    	<?php echo $frm->getElement('province');?>
			                   </div>
			                </div>
			                <div class="form-group">
			                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("DISTRICT");?> :
			                   </label>
			                   <div class="col-md-7 col-sm-7 col-xs-12">
			                    	<input id="district" required="true" >
			                   </div>
			                </div>
			                <div class="form-group">
			                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("COMMUNE");?>  :
			                   </label>
			                   <div class="col-md-7 col-sm-7 col-xs-12">
			                    	<input id="commune" >
			                   </div>
			                </div>
			                <div class="form-group">
			                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("VILLAGE");?>  :
			                   </label>
			                   <div class="col-md-7 col-sm-7 col-xs-12">
			                    	<input id="village" >
			                   </div>
			                </div>
			                <div class="form-group">
			                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("MAP");?> :
			                   </label>
			                   <div class="col-md-7 col-sm-7 col-xs-12">
			                    	<?php  echo $frm->getElement('map');?>
			                   </div>
			                </div>
			            </div>
			            <div class="col-md-4 col-sm-4 col-xs-12">
							<div class="form-group">
			                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" for="first-name"><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("OTHER_INFO");?> 
			                   </label>
			                </div>
			                <div class="form-group">
			                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("SIDE");?>  :
			                   </label>
			                   <div class="col-md-7 col-sm-7 col-xs-12">
			                    	<?php  echo $frm->getElement('side');?>
			                   </div>
			                </div>
			                <div class="form-group">
			                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("START_DIRECTION");?>  :
			                   </label>
			                   <div class="col-md-7 col-sm-7 col-xs-12">
			                    	<?php  echo $frm->getElement('start_direction');?>
			                   </div>
			                </div>
			                <div class="form-group">
			                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("OTHER");?>  :
			                   </label>
			                   <div class="col-md-7 col-sm-7 col-xs-12">
			                    	<?php  echo $frm->getElement('other');?>
			                   </div>
			                </div>
			                <div class="form-group">
			                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("NOTE");?> :
			                   </label>
			                   <div class="col-md-7 col-sm-7 col-xs-12">
			                    	<?php  echo $frm->getElement('noted');?>
			                   </div>
			                </div>
			            </div>
			        </div>
			        <!--/.Panel 1-->
			         <!--Panel 2-->
			        <div class="tab-pane fade in " id="panel22" role="tabpanel">
			        	<div class="form-group">
			        		<table class="history-record" >
		                		<thead>
		                			<tr>
		                				<th><?php echo $tr->translate("NUM");?></th>
		                				<th><?php echo $tr->translate("MOVE_FROM");?></th>
		                				<th><?php echo $tr->translate("MOVE_TO");?></th>
		                				<th><?php echo $tr->translate("NOTE");?></th>
		                				<th></th>
		                			</tr>
		                		</thead>
		                		<tbody>
		                			<?php if (!empty($this->movinghist)) foreach ($this->movinghist as $key => $rs){?>
		                			<tr>
		                				<td align="center"><?php echo $key+1;?></td>
		                				<td>
		                					<?php echo $tr->translate("ZONE")." : ".$rs['zone'];
		                						echo empty($rs['street'])?"":", ".$tr->translate("STREET")." : ".$rs['street'];
		                						echo empty($rs['line'])?"":", ".$tr->translate("LINE")." : ".$rs['line'];
		                						echo empty($rs['floor'])?"":", ".$tr->translate("FLOOR")." : ".$rs['floor'];
		                						echo empty($rs['side'])?"":", ".$tr->translate("SIDE")." : ".$rs['side'];
		                						echo empty($rs['start_direction'])?"":", ".$tr->translate("START_DIRECTION")." : ".$rs['start_direction'];
		                						echo "<br />";
		                						echo empty($rs['province'])?"":"".$tr->translate("PROVINCE")." : ".$rs['province'];
		                						echo empty($rs['district'])?"":", ".$tr->translate("DISTRICT")." : ".$rs['district'];
		                						echo empty($rs['commnune'])?"":", ".$tr->translate("COMMUNE")." : ".$rs['commnune'];
		                						echo empty($rs['village_name'])?"":", ".$tr->translate("VILLAGE")." : ".$rs['village_name'];
		                					?>
		                				</td>
		                				<td>
		                					<?php echo $tr->translate("ZONE")." : ".$rs['new_zone'];
		                						echo empty($rs['new_street'])?"":", ".$tr->translate("STREET")." : ".$rs['new_street'];
		                						echo empty($rs['new_line'])?"":", ".$tr->translate("LINE")." : ".$rs['new_line'];
		                						echo empty($rs['new_floor'])?"":", ".$tr->translate("FLOOR")." : ".$rs['new_floor'];
		                						echo empty($rs['new_side'])?"":", ".$tr->translate("SIDE")." : ".$rs['new_side'];
		                						echo empty($rs['new_start_direction'])?"":", ".$tr->translate("START_DIRECTION")." : ".$rs['new_start_direction'];
		                						echo "<br />";
		                						echo empty($rs['new_province'])?"":"".$tr->translate("PROVINCE")." : ".$rs['new_province'];
		                						echo empty($rs['new_district'])?"":", ".$tr->translate("DISTRICT")." : ".$rs['new_district'];
		                						echo empty($rs['new_commnune'])?"":", ".$tr->translate("COMMUNE")." : ".$rs['new_commnune'];
		                						echo empty($rs['new_village_name'])?"":", ".$tr->translate("VILLAGE")." : ".$rs['new_village_name'];
		                					?>
		                				</td>
		                				<td><?php echo $rs['note'];?></td>
		                			</tr>
		                			<?php }?>
		                		</tbody>
		             		</table>
			             </div>
			        </div>
			        <!--/.Panel 2-->
			    </div>
			</div>
			<div class="clearfix"></div>
			    <div class="card-box">
               		<div class="col-sm-12 border-top mt-20 ptb-10 text-center">
					 <input type="submit" value="SAVE_CLOSE" tabindex="2" label="<?php echo $tr->translate('SAVECLOSE');?>" id="save_close" dojoType="dijit.form.Button" name="save_close"
						 iconClass="dijitEditorIcon dijitEditorIconSave" /> 
	    		</div>
	    	</div>
		</form>
	</div>
</div>
<style>
table.history-record {
    width: 100%;
    font-size: 12px;
}
table.history-record thead tr th {
    text-align: center;
    padding: 5px 2px;
    background: #e0eafb;
    border-bottom: solid 1px #afadad;
	    border: solid 1px #ccc;
}
table.history-record tbody tr {
    border-bottom: solid 1px #e8e8e8;
}
table.history-record tbody tr td {
    padding: 5px;
	vertical-align: top;
}
a.btn.btn-primary.btn-xs {
    margin-bottom: -2px;
    padding: 1px 5px;
    background: #02014a;
    border: solid 1px #3d3c7d;
}  
</style>
<?php 
	echo $this->frm_popup_district;
	echo $this->frm_popup_village;
	echo $this->frm_popup_comm;
	echo $this->frm_popupOther;
	
	echo $this->frmPopupStreet;
	echo $this->frmPopupZone;
	echo $this->frmPopupCate;
	
?>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script>
	dojo.require("dojo.data.ItemFileWriteStore");  
	dojo.require("dijit.form.DateTextBox");
	dojo.require("dijit.form.Textarea");
	dojo.require("dijit.form.NumberTextBox");
	dojo.require("dijit.Dialog");
</script>
<script type="text/javascript">
var other_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->other));?> );
var floor_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->floor));?> );
var line_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->line));?> );
var side_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->side));?> );
var start_direction_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->start_direction));?> );
require(["dojo/ready"], function(ready){
	new dijit.form.FilteringSelect({
		name: "other",
		id: "other",
		autoComplete: false,
		queryExpr: "*${0}*",     
		searchAttr: "name",
		class: 'fullside',
		onChange: function() {
			popupFormData(1);
	    }
	}, "other");
	new dijit.form.FilteringSelect({
		name: "floor",
		id: "floor",
		autoComplete: false,
		queryExpr: "*${0}*",     
		searchAttr: "name",
		class: 'fullside',
		onChange: function() {
			popupFormData(2);
	    }
	}, "floor");
	new dijit.form.FilteringSelect({
		name: "line",
		id: "line",
		autoComplete: false,
		queryExpr: "*${0}*",     
		searchAttr: "name",
		class: 'fullside',
		onChange: function() {
			popupFormData(3);
	    }
	}, "line");
	new dijit.form.FilteringSelect({
		name: "side",
		id: "side",
		autoComplete: false,
		queryExpr: "*${0}*",     
		searchAttr: "name",
		class: 'fullside',
		onChange: function() {
			popupFormData(4);
	    }
	}, "side");
	new dijit.form.FilteringSelect({
		name: "start_direction",
		id: "start_direction",
		autoComplete: false,
		queryExpr: "*${0}*",     
		searchAttr: "name",
		class: 'fullside',
		onChange: function() {
			popupFormData(5);
	    }
	}, "start_direction");


	new dijit.form.FilteringSelect({
		name: "street_id",
		id: "street_id",
		autoComplete: false,
		queryExpr: "*${0}*",     
		searchAttr: "name",
		class: 'fullside',
		onChange: function() {
			popupFormDataCate(5);
	    }
	}, "street_id");

	new dijit.form.FilteringSelect({
		name: "zone_id",
		id: "zone_id",
		autoComplete: false,
		queryExpr: "*${0}*",     
		searchAttr: "name",
		class: 'fullside',
		onChange: function() {
			popupFormDataCate(6);
	    }
	}, "zone_id");

	new dijit.form.FilteringSelect({
		name: "category",
		id: "category",
		autoComplete: false,
		queryExpr: "*${0}*",     
		searchAttr: "name",
		class: 'fullside',
		onChange: function() {
			popupCategory();
	    }
	}, "category");
});
function popupFormDataCate(index){
	if(index==1){
	}else if(index==2){
	}else if(index==3){
	}else if(index==4){	
	}else if(index==5){
		street_id = dijit.byId('street_id').get('value');
		if(street_id==-1){
			dijit.byId("frm_datapop_street").show();
		}
	}else if(index==6){
		zone_id = dijit.byId('zone_id').get('value');
		if(zone_id==-1){
			dijit.byId("frm_datapop_zone").show();
		}
	}
}
var street_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->street));?> );
function addStreetd(){
	var url_ajax = '<?php echo $this->url(array('module'=>'other','controller'=>'street','action'=>'addajax')); ?>';
	if(dijit.byId('form_popup_street').validate()){
		dojo.xhrPost({
			url: url_ajax,
			form: dojo.byId("form_popup_street"),
			handleAs:"json",
			load: function(data) {
				var Itemmake = {					
						id: data,
						name: dijit.byId('str_no').get('value')+' - '+dijit.byId('str_title').get('value')
				};
				addDataToSelectbox(dijit.byId('street_id'),street_store , Itemmake, data);
				dijit.byId('form_popup_street').reset();
				dijit.byId("frm_datapop_street").hide();
			},
			error: function(err) {
				alert(err);
			}
		});
	}
}
var zone_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->zone));?> );
function addZone(){
	var url_ajax = '<?php echo $this->url(array('module'=>'other','controller'=>'zone','action'=>'addajax')); ?>';
	if(dijit.byId('form_popup_zone').validate()){
		dojo.xhrPost({
			url: url_ajax,
			form: dojo.byId("form_popup_zone"),
			handleAs:"json",
			load: function(data) {
				var Itemmake = {					
						id: data,
						name: dijit.byId('title_zone').get('value')
				};
				addDataToSelectbox(dijit.byId('zone_id'),zone_store , Itemmake, data);
				dijit.byId('form_popup_zone').reset();
				dijit.byId("frm_datapop_zone").hide();
			},
			error: function(err) {
				alert(err);
			}
		});
	}
}
function popupFormData(index){
	dijit.byId('type').set('value',index);
	if(index==1){
		controlvalue = dijit.byId('other').get('value');
		$("#title_form").html("<?php echo $tr->translate("ADD_OTHER");?>");
	}else if(index==2){
		controlvalue = dijit.byId('floor').get('value');
		$("#title_form").html("<?php echo $tr->translate("ADD_FLOOR");?>");
	}else if(index==3){
		controlvalue = dijit.byId('line').get('value');
		$("#title_form").html("<?php echo $tr->translate("ADD_LINE");?>");
	}else if(index==4){
		controlvalue = dijit.byId('side').get('value');
		$("#title_form").html("<?php echo $tr->translate("ADD_SIDE");?>");
	}else if(index==5){
		controlvalue = dijit.byId('start_direction').get('value');
		$("#title_form").html("<?php echo $tr->translate("ADD_START_DIRECTION");?>");
	}else if(index==6){
		controlvalue = dijit.byId('verification').get('value');
		$("#title_form").html("<?php echo $tr->translate("ADD_VERIFICATION");?>");
	}
	if(controlvalue==-1){
		dijit.byId("frm_datapop").show();
	}
}
var url_branch = '<?php echo $this->url(array('module'=>'other','controller'=>'index','action'=>'addnewdata')); ?>';
function addData(){
	if(dijit.byId('form_popup').validate()){
		dojo.xhrPost({
			url:url_branch,
			form: dojo.byId("form_popup"),
			handleAs:"json",
			load: function(data) {
				var Itemmake = {					
						id: data,
						name: dijit.byId('title').get('value')
				};
				var type = dijit.byId('type').get('value');	
				if(type==1){
					addDataToSelectbox(dijit.byId('other'),other_store , Itemmake, data);
				}else if(type==2){
					addDataToSelectbox(dijit.byId('floor'),floor_store , Itemmake, data);
				}else if(type==3){
					addDataToSelectbox(dijit.byId('line'),line_store , Itemmake, data);
				}else if(type==4){
					addDataToSelectbox(dijit.byId('side'),side_store , Itemmake, data);
				}else if(type==5){
					addDataToSelectbox(dijit.byId('start_direction'),start_direction_store , Itemmake, data);
				}else if(type==6){
					addDataToSelectbox(dijit.byId('verification'),verification_store , Itemmake, data);
				}	
				dijit.byId('form_popup').reset();
				dijit.byId("frm_datapop").hide();
			},
			error: function(err) {
				alert(err);
			}
		});
	}
}
var district_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?> );
var commune_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?> );
var village_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?> );

dojo.ready(function(){
	try{
		new dijit.form.FilteringSelect({
		store: district_store,
		autoComplete:false,
		queryExpr:'*${0}*',
		required: false,		           
		name: "district",
		id: "district",
		searchAttr: "name",
		class: 'fullside',
			onChange: function() {
				district = dijit.byId('district').get('value');
				if(district==-1){
					showPopupdistrict();
					}
					filterCommune();
			}  
		}, "district");
	 
		new dijit.form.FilteringSelect({
		store: commune,
		autoComplete:false,
		queryExpr:'*${0}*',
		required: false,		           
		name: "commune",
		id: "commune",
		searchAttr: "name",
		class: 'fullside',
			onChange: function() {
				commune = dijit.byId('commune').get('value');
				if(commune==-1){
					showPopupCommune();
				}
				else{
					filterVillage();
				}
	  		}
		}, "commune");

		new dijit.form.FilteringSelect({
		store: village_store,
		autoComplete:false,
		queryExpr:'*${0}*',
		required: false,		           
		name: "village",
		id: "village",
		searchAttr: "name",
		class: 'fullside',
			onChange: function() {
				vill = dijit.byId('village').get('value');
				if(vill==-1){
					showPopupVillage();
				}
			}
	
		}, "village");
		getClientNo();
	}catch(e){
	}
});


url_getdistrict = '<?php echo $this->url(array('module'=>'other','controller'=>'district','action'=>'get-district'));?>';
function filterDistrict(){
	pro_id = dijit.byId('province').get('value');
	if(pro_id==0){
		return false;}
	dojo.xhrPost({
		url:url_getdistrict,	
		content:{ 
			'pro_id': pro_id
		},
		handleAs:"json",
		load: function(data) {	
			district_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('district').set('store', district_store);
		},
		error: function(err) {
		}
	});	
}
url_getcommune = '<?php echo $this->url(array('module'=>'other','controller'=>'commune','action'=>'get-commune'));?>';
function filterCommune(){
	distict_id = dijit.byId('district').get('value');
	if(distict_id==0){
		return false;}
	dojo.xhrPost({
		url:url_getcommune,	
		content:{ 
			'district_id': distict_id
		},
		handleAs:"json",
		load: function(data) {	
			commune_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('commune').set('store', commune_store);
		},
		error: function(err) {
		}
	});
}
url_getvillage = '<?php echo $this->url(array('module'=>'other','controller'=>'village','action'=>'get-allvillage'));?>';
function filterVillage(){
		commune_id = dijit.byId('commune').get('value');
		if(commune_id==0){
			return false;
		}
		dojo.xhrPost({
			url:url_getvillage,	
			content:{ 
				'commune_id': commune_id
			},
			handleAs:"json",
			load: function(data) {	
				village_store  = getDataStorefromJSON('id','name', data);		
			    dijit.byId('village').set('store', village_store);
			},
			error: function(err) {
			}
		});
}

client_village = '<?php echo $this->url(array('module'=>'other','controller'=>'village','action'=>'add-village'));?>';
function addVillage(){
	if(dijit.byId('frm_village').validate()){
		loadingBlock();
		dojo.xhrPost({
			url:client_village,	
			form:dojo.byId('form_village'),
			handleAs:"json",
			load: function(data) {
				labelkh = dijit.byId('village_namekh').get('value');
				var villageItem1 = {					
						id: data,
						name: labelkh,
				};			
				addDataToSelectbox(dijit.byId('village'), village_store, villageItem1, data);	
				dijit.byId('frm_village').reset();
				dijit.byId('frm_village').hide();
				HideloadingBlock();
			},
			error: function(err) {
			}
		});
	}
}
function showPopupVillage(){
	communeid = dijit.byId('commune').get('value');
	if(communeid!=-1){
		province_id = dijit.byId('province').get('value');
		dijit.byId('province_name').attr('value',province_id);
		dijit.byId('province_name').set('readOnly',true);

		district_name=province_id = dijit.byId('district').get('value');
		dijit.byId('district_name').attr('value',district_name);
		dijit.byId('district_name').set('readOnly',true);

		dijit.byId('commune_name').attr('value',communeid);
		dijit.byId('commune_name').set('readOnly',true);
		dijit.byId('frm_village').show();
	}else{
		alert('please select commune first');
		dijit.byId('commune').focus();
	}
}
function showPopupCommune(){
	district = dijit.byId('district').get('value');
	if(district!=-1){
		dijit.byId('district_nameen').attr('value',district);
		dijit.byId('district_nameen').set('readOnly',true);
		dijit.byId('frm_commune').show();
	}else{
		alert('please select district first');
		dijit.byId('district').focus();
	}
}
function showPopupdistrict(){
	province_id = dijit.byId('province').get('value');
	if(province_id!=0){
		dijit.byId('province_names').attr('value',province_id);
		dijit.byId('province_names').set('readOnly',true);
		dijit.byId('frm_district').show();
	}else{
		alert('please select province first');
		dijit.byId('province').focus();
	}
}
function dshowPopupVillage(){
	communeid = dijit.byId('dcommune').get('value');
	if(communeid!=-1){
		province_id = dijit.byId('cprovince').get('value');
		dijit.byId('province_name').attr('value',province_id);
		dijit.byId('province_name').set('readOnly',true);

		district_name=province_id = dijit.byId('adistrict').get('value');
		dijit.byId('district_name').attr('value',district_name);
		dijit.byId('district_name').set('readOnly',true);

		dijit.byId('commune_name').attr('value',communeid);
		dijit.byId('commune_name').set('readOnly',true);
		dijit.byId('frm_village').show();
	}else{
		alert('please select commune first');
		dijit.byId('dcommune').focus();
	}
}
function dshowPopupCommune(){
	district = dijit.byId('adistrict').get('value');
	if(district!=-1){
		dijit.byId('district_nameen').attr('value',district);
		dijit.byId('district_nameen').set('readOnly',true);
		dijit.byId('frm_commune').show();
	}else{
		alert('please select district first');
		dijit.byId('adistrict').focus();
	}
}
function dshowPopupdistrict(){
	province_id = dijit.byId('province').get('value');
	if(province_id!=0){
		dijit.byId('province_names').attr('value',province_id);
		dijit.byId('province_names').set('readOnly',true);
		dijit.byId('frm_district').show();
	}else{
		alert('please select province first');
		dijit.byId('province').focus();
	}
}
var district_url = '<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'insert-district'));?>';
function addNewDistrict(){
	if(dijit.byId('frm_district').validate()){
		loadingBlock();
		dojo.xhrPost({
			url:district_url,	
			form:dojo.byId('form_district'),
			handleAs:"json",
			load: function(data){	
				var myNewItem1 = {					
						id: data,
						name: dijit.byId('pop_district_namekh').get('value'),
				};			
				addDataToSelectbox(dijit.byId('district'), district_store, myNewItem1, data);	
				dijit.byId('frm_district').reset();
				dijit.byId('frm_district').hide();
				HideloadingBlock();
			},
			error: function(err){
			}
		});	
	}
}
var commune_url = '<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'insertcommune'));?>';
function addNewCommune(){
	if(dijit.byId('frm_commune').validate()) {
		loadingBlock();
		dojo.xhrPost({
			url:commune_url,	
			form:dojo.byId('form_commune'),
			handleAs:"json",
			load: function(data) {	
				
				communekh = dijit.byId('commune_namekh').get('value');
				var Itemcommune = {					
						id: data,
						name: communekh,
				};			
				addDataToSelectbox(dijit.byId('commune'), commune_store, Itemcommune, data);
				dijit.byId('frm_commune').reset();
				dijit.byId('frm_commune').hide();
				HideloadingBlock();
			},
			error: function(err) {
			}
		});
	}
}

</script>
